### ISSUE TITLE
Crash in destructor ~ _AutoDeleter() ~_ContinuationTaskHandle

### ISSUE THREAD

**Issue by KapilGokhale** [microsoft/cpprestsdk#1255]
- Our test environment is ubuntu 18.04.
- (Applications developed by us) Processes - which communicate over casablanca on localhost - each one of them is pinned to a single core. The load is not too high though. There might be at maximum 30 http clients connecting to this concenred application at any given point of time.
- Below image mentioned the casablanca code base in use. It is latest available as per today. (2.10.14).
![image](https://user-images.githubusercontent.com/6161155/65949311-94222a00-e459-11e9-92b3-cb228f317d57.png)
- Added -g debug flag [This is the only change]
![image](https://user-images.githubusercontent.com/6161155/65949505-f844ee00-e459-11e9-97cf-7ade4fdb97f7.png)
- Getting a crash SIGTRAP with bt mentioned below
- The bt does not point to line numbers from application code.
- Function ausf::ausfNudm_SDM_Get_AuthInfo (application code) is registered.
- Wonder if there is a bug in Casablanca. If not the please suggest what could be going wrong.
- If yes then is there a solution available?

```
(gdb) bt
#0  raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x000055555561f76e in pplx::details::_ExceptionHolder::~_ExceptionHolder (this=0x7fff60043920, __in_chrg=<optimized out>)
    at /home/g02/libcpprest-dev-clone/cpprestsdk/Release/include/pplx/pplxtasks.h:952
#2  0x000055555562db40 in __gnu_cxx::new_allocator<pplx::details::_ExceptionHolder>::destroy<pplx::details::_ExceptionHolder> (this=0x7fff60043920, __p=0x7fff60043920)
    at /usr/include/c++/7/ext/new_allocator.h:140
#3  0x000055555562da51 in std::allocator_traits<std::allocator<pplx::details::_ExceptionHolder> >::destroy<pplx::details::_ExceptionHolder> (__a=..., __p=0x7fff60043920)
    at /usr/include/c++/7/bits/alloc_traits.h:487
#4  0x000055555562d739 in std::_Sp_counted_ptr_inplace<pplx::details::_ExceptionHolder, std::allocator<pplx::details::_ExceptionHolder>, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x7fff60043910)
    at /usr/include/c++/7/bits/shared_ptr_base.h:535
#5  0x00005555556234ec in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x7fff60043910) at /usr/include/c++/7/bits/shared_ptr_base.h:154
#6  0x0000555555621e81 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x7fff4c0aaca8, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/shared_ptr_base.h:684
#7  0x000055555561f832 in std::__shared_ptr<pplx::details::_ExceptionHolder, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x7fff4c0aaca0, __in_chrg=<optimized out>)
    at /usr/include/c++/7/bits/shared_ptr_base.h:1123
#8  0x000055555561f84e in std::shared_ptr<pplx::details::_ExceptionHolder>::~shared_ptr (this=0x7fff4c0aaca0, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/shared_ptr.h:93
#9  0x0000555555645950 in pplx::details::_Task_impl_base::~_Task_impl_base (this=0x7fff4c0aac90, __in_chrg=<optimized out>)
    at /home/g02/libcpprest-dev-clone/cpprestsdk/Release/include/pplx/pplxtasks.h:1718
#10 0x000055555565876e in pplx::details::_Task_impl<unsigned char>::~_Task_impl (this=0x7fff4c0aac90, __in_chrg=<optimized out>)
    at /home/g02/libcpprest-dev-clone/cpprestsdk/Release/include/pplx/pplxtasks.h:2425
#11 0x000055555565b98f in __gnu_cxx::new_allocator<pplx::details::_Task_impl<unsigned char> >::destroy<pplx::details::_Task_impl<unsigned char> > (this=0x7fff4c0aac90, __p=0x7fff4c0aac90)
    at /usr/include/c++/7/ext/new_allocator.h:140
#12 0x0000555555658c1f in std::allocator_traits<std::allocator<pplx::details::_Task_impl<unsigned char> > >::destroy<pplx::details::_Task_impl<unsigned char> > (__a=..., __p=0x7fff4c0aac90)
    at /usr/include/c++/7/bits/alloc_traits.h:487
#13 0x0000555555653b8b in std::_Sp_counted_ptr_inplace<pplx::details::_Task_impl<unsigned char>, std::allocator<pplx::details::_Task_impl<unsigned char> >, (__gnu_cxx::_Lock_policy)2>::_M_dispose (
    this=0x7fff4c0aac80) at /usr/include/c++/7/bits/shared_ptr_base.h:535
#14 0x00005555556234ec in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x7fff4c0aac80) at /usr/include/c++/7/bits/shared_ptr_base.h:154
#15 0x0000555555621e81 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x7fffcc041840, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/shared_ptr_base.h:684
#16 0x000055555561fc26 in std::__shared_ptr<pplx::details::_Task_impl<unsigned char>, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x7fffcc041838, __in_chrg=<optimized out>)
    at /usr/include/c++/7/bits/shared_ptr_base.h:1123
#17 0x000055555561fc42 in std::shared_ptr<pplx::details::_Task_impl<unsigned char> >::~shared_ptr (this=0x7fffcc041838, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/shared_ptr.h:93
#18 0x000055555567f93a in pplx::details::_PPLTaskHandle<unsigned char, pplx::task<web::json::value>::_ContinuationTaskHandle<web::json::value, void, ausf::ausfNudm_SDM_Get_AuthInfo(void*)::<lambda(pplx::task<web::http::http_response>)>::<lambda(pplx::task<web::json::value>)>, std::integral_constant<bool, true>, pplx::details::_TypeSelectorNoAsync>, pplx::details::_ContinuationTaskHandleBase>::~_PPLTaskHandle(void) (this=0x7fffcc041820, __in_chrg=<optimized out>) at /home/g02/libcpprest-dev-clone/cpprestsdk/Release/include/pplx/pplxtasks.h:1628
#19 0x00005555556806e2 in pplx::task<web::json::value>::_ContinuationTaskHandle<web::json::value, void, ausf::ausfNudm_SDM_Get_AuthInfo(void*)::<lambda(pplx::task<web::http::http_response>)>::<lambda(pplx::task<web::json::value>)>, std::integral_constant<bool, true>, pplx::details::_TypeSelectorNoAsync>::~_ContinuationTaskHandle(void) (this=0x7fffcc041820, __in_chrg=<optimized out>)
    at /home/g02/libcpprest-dev-clone/cpprestsdk/Release/include/pplx/pplxtasks.h:3927
#20 0x00005555556806fe in pplx::task<web::json::value>::_ContinuationTaskHandle<web::json::value, void, ausf::ausfNudm_SDM_Get_AuthInfo(void*)::<lambda(pplx::task<web::http::http_response>)>::<lambda(pplx::task<web::json::value>)>, std::integral_constant<bool, true>, pplx::details::_TypeSelectorNoAsync>::~_ContinuationTaskHandle(void) (this=0x7fffcc041820, __in_chrg=<optimized out>)
    at /home/g02/libcpprest-dev-clone/cpprestsdk/Release/include/pplx/pplxtasks.h:3927
#21 0x0000555555647c8d in pplx::details::_AutoDeleter<pplx::details::_TaskProcHandle>::~_AutoDeleter (this=0x7fffec3f0a78, __in_chrg=<optimized out>)
    at /home/g02/libcpprest-dev-clone/cpprestsdk/Release/include/pplx/pplx.h:98
#22 0x0000555555644f38 in pplx::details::_TaskProcHandle::_RunChoreBridge (_Parameter=0x7fffcc041820) at /home/g02/libcpprest-dev-clone/cpprestsdk/Release/include/pplx/pplx.h:112
#23 0x00007ffff70a6ebb in boost::_bi::list1<boost::_bi::value<void*> >::operator()<void (*)(void*), boost::_bi::list0> (this=0x7fffec3f0c68,
    f=@0x7fffec3f0c60: 0x555555644ede <pplx::details::_TaskProcHandle::_RunChoreBridge(void*)>, a=...) at /usr/include/boost/bind/bind.hpp:259
#24 0x00007ffff70a6e56 in boost::_bi::bind_t<void, void (*)(void*), boost::_bi::list1<boost::_bi::value<void*> > >::operator() (this=0x7fffec3f0c60) at /usr/include/boost/bind/bind.hpp:1294
#25 0x00007ffff70a6e09 in boost::asio::asio_handler_invoke<boost::_bi::bind_t<void, void (*)(void*), boost::_bi::list1<boost::_bi::value<void*> > > > (function=...)
    at /usr/include/boost/asio/handler_invoke_hook.hpp:69
#26 0x00007ffff70a6d9e in boost_asio_handler_invoke_helpers::invoke<boost::_bi::bind_t<void, void (*)(void*), boost::_bi::list1<boost::_bi::value<void*> > >, boost::_bi::bind_t<void, void (*)(void*), boost::_bi::list1<boost::_bi::value<void*> > > > (function=..., context=...) at /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#27 0x00007ffff70a6ccc in boost::asio::detail::completion_handler<boost::_bi::bind_t<void, void (*)(void*), boost::_bi::list1<boost::_bi::value<void*> > > >::do_complete (owner=0x55555597b350,
    base=0x7fff8c088490) at /usr/include/boost/asio/detail/completion_handler.hpp:68
#28 0x00007ffff6fa77a6 in boost::asio::detail::task_io_service_operation::complete (this=0x7fff8c088490, owner=..., ec=..., bytes_transferred=0)
    at /usr/include/boost/asio/detail/task_io_service_operation.hpp:38
#29 0x00007ffff6faa7cf in boost::asio::detail::task_io_service::do_run_one (this=0x55555597b350, lock=..., this_thread=..., ec=...) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:372
---Type <return> to continue, or q <return> to quit---
#30 0x00007ffff6faa10f in boost::asio::detail::task_io_service::run (this=0x55555597b350, ec=...) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:149
#31 0x00007ffff6faaade in boost::asio::io_service::run (this=0x7ffff74e59e8 <(anonymous namespace)::initialize_shared_threadpool(unsigned long)::uninit_threadpool+8>)
    at /usr/include/boost/asio/impl/io_service.ipp:59
#32 0x00007ffff70a8a95 in (anonymous namespace)::threadpool_impl::thread_start (arg=0x7ffff74e59e0 <(anonymous namespace)::initialize_shared_threadpool(unsigned long)::uninit_threadpool>)
    at /home/g02/libcpprest-dev-clone/cpprestsdk/Release/src/pplx/threadpool.cpp:79
#33 0x00007ffff70a89a5 in (anonymous namespace)::threadpool_impl::<lambda()>::operator()(void) const (__closure=0x555555982eb8)
    at /home/g02/libcpprest-dev-clone/cpprestsdk/Release/src/pplx/threadpool.cpp:64
#34 0x00007ffff70a9392 in boost::asio::detail::posix_thread::func<(anonymous namespace)::threadpool_impl::add_thread()::<lambda()> >::run(void) (this=0x555555982eb0)
    at /usr/include/boost/asio/detail/posix_thread.hpp:82
#35 0x00007ffff6fb06bf in boost::asio::detail::boost_asio_detail_posix_thread_function (arg=0x555555982eb0) at /usr/include/boost/asio/detail/impl/posix_thread.ipp:64
#36 0x00007ffff74ed6db in start_thread (arg=0x7fffec3f1700) at pthread_create.c:463
#37 0x00007ffff59b688f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 
```

**Comment by HappyCerberus** [comment]
I might be running into the same problem: https://github.com/microsoft/cpprestsdk/issues/1497
Did you manage to figure this out?
