### ISSUE TITLE
Missing CRLF in Authorization Line

### ISSUE THREAD

**Issue by forty-lanterns** [microsoft/cpprestsdk#1261]
Hello. This appears to be an issue in the cpprest which prevents a client from connecting to a server. My apologies if it is a user error. The issue is seen when using libcpprest 2.10.13.

When a user creates a connection using "new websocket_client(config)", the Authorization line may be missing a CR. This results in some servers (python 3.6 websockets library) spewing the following error on an attempt to connect.

Invalid handshake
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/server.py", line 174, in read_http_request
    path, headers = yield from read_request(self.reader)
  File "/usr/lib/python3/dist-packages/websockets/http.py", line 89, in read_request
    headers = yield from read_headers(stream)
  File "/usr/lib/python3/dist-packages/websockets/http.py", line 157, in read_headers
    line = yield from read_line(stream)
  File "/usr/lib/python3/dist-packages/websockets/http.py", line 195, in read_line
    raise ValueError("Line without CRLF")
ValueError: Line without CRLF

An inspection of the traffic using wireshark reveals that the Authorization line (which has been populated with the string "hello") contains only a newline, and not a carriage return in the initial Upgrade message:

![bug](https://user-images.githubusercontent.com/33579463/66970673-1e19e780-f043-11e9-8618-e5d3a8b67f4f.png)

**Comment by forty-lanterns** [comment]
I have narrowed this down to something that can be fixed by trimming a string in the client code. However, I leave this here so someone can ponder (and possibly reject) the idea of trimming the input token in the cpprest itself.
