### ISSUE TITLE
Crash happen when I upgrade from GCC4.8.5 to GCC4.9.4

### ISSUE THREAD

**Issue by laoshanxi** [microsoft/cpprestsdk#1389]
I rebuilt cpprestsdk and boost169, and cpprestsdk can not pass build so I changed to a earlier version, but still found crash when request http:
```
(gdb) bt
#0  0x00007ffff70a98b4 in Concurrency::streams::basic_ostream<unsigned char>::_verify_and_throw(char const*) const () from /opt/appmanager/lib64/libcpprest.so.2.10
#1  0x00007ffff709f8c0 in web::http::details::http_msg_base::_prepare_to_receive_data() () from /opt/appmanager/lib64/libcpprest.so.2.10
#2  0x00007ffff708b65a in web::http::client::details::request_context::request_context(std::shared_ptr<web::http::client::details::_http_client_communicator> const&, web::http::http_request const&) ()
   from /opt/appmanager/lib64/libcpprest.so.2.10
#3  0x00007ffff7181201 in web::http::client::details::asio_context::create_request_context(std::shared_ptr<web::http::client::details::_http_client_communicator>&, web::http::http_request&) ()
   from /opt/appmanager/lib64/libcpprest.so.2.10
#4  0x00007ffff71763ab in web::http::client::details::asio_client::propagate(web::http::http_request) () from /opt/appmanager/lib64/libcpprest.so.2.10
#5  0x00007ffff7093699 in web::http::oauth2::details::oauth2_handler::propagate(web::http::http_request) () from /opt/appmanager/lib64/libcpprest.so.2.10
#6  0x00007ffff7093c06 in web::http::oauth1::details::oauth1_handler::propagate(web::http::http_request) () from /opt/appmanager/lib64/libcpprest.so.2.10
#7  0x00007ffff708cd7d in web::http::client::http_client::request(web::http::http_request, pplx::cancellation_token const&) () from /opt/appmanager/lib64/libcpprest.so.2.10
```
can any one knowns this issue and what's the suggest GCC version for the master branch?

**Comment by laoshanxi** [comment]
Related to this issue:
https://github.com/microsoft/cpprestsdk/issues/1391
