### ISSUE TITLE
libcpprest.so.2.10 crashed with "https" when "GET" on any valid server

### ISSUE THREAD

**Issue by everdancer** [microsoft/cpprestsdk#1524]
```
Program terminated with signal 11, Segmentation fault.
#0  0x00007fdf16b94111 in boost::asio::ssl::detail::engine::map_error_code(boost::system::error_code&) const () from /lib64/libcpprest.so.2.10
Missing separate debuginfos, use: debuginfo-install glibc-2.17-307.el7.1.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-46.el7.x86_64 libcom_err-1.42.9-17.el7.x86_64 libgcc-4.8.5-39.el7.x86_64 libselinux-2.5-15.el7.x86_64 libstdc++-4.8.5-39.el7.x86_64 nss-softokn-freebl-3.44.0-8.el7_7.x86_64 openssl-libs-1.0.2k-19.el7.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) bt
**#0  0x00007fdf16b94111 in boost::asio::ssl::detail::engine::map_error_code(boost::system::error_code&) const () from /lib64/libcpprest.so.2.10**
#1  0x00007fdf16c25f00 in boost::asio::ssl::detail::io_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::ssl::detail::handshake_op, boost::_bi::bind_t<void, boost::_mfi::mf1<void, web::http::client::details::asio_context, boost::system::error_code const&>, boost::_bi::list2<boost::_bi::value<std::shared_ptr<web::http::client::details::asio_context> >, boost::arg<1> (*)()> > >::operator()(boost::system::error_code, unsigned long, int) () from /lib64/libcpprest.so.2.10
#2  0x00007fdf16c26978 in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::asio::ssl::detail::io_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::ssl::detail::handshake_op, boost::_bi::bind_t<void, boost::_mfi::mf1<void, web::http::client::details::asio_context, boost::system::error_code const&>, boost::_bi::list2<boost::_bi::value<std::shared_ptr<web::http::client::details::asio_context> >, boost::arg<1> (*)()> > > >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) () from /lib64/libcpprest.so.2.10
#3  0x00007fdf16b981ab in boost::asio::detail::scheduler::run(boost::system::error_code&) () from /lib64/libcpprest.so.2.10
#4  0x00007fdf16c122bd in boost::asio::detail::posix_thread::func<(anonymous namespace)::threadpool_impl::add_thread()::{lambda()#1}>::run() () from /lib64/libcpprest.so.2.10
#5  0x00007fdf16b896ef in boost_asio_detail_posix_thread_function () from /lib64/libcpprest.so.2.10
#6  0x00007fdf15fa6ea5 in start_thread () from /lib64/libpthread.so.0
#7  0x00007fdf15ccf8dd in clone () from /lib64/libc.so.6

```

Code is as below. It will be the same issue even if changing to other "https" url. Tried set_validate_certificates(false) with http_client_config, didn't help.
```
#include <cpprest/http_client.h>
#include <cpprest/filestream.h>
#include <cpprest/uri.h>
#include <cpprest/json.h>

using namespace std;
using namespace utility;
using namespace web;
using namespace web::http;
using namespace web::http::client;

int main ()
{
    auto* mp_client = new http_client(U("https://en.wikipedia.org/wiki/HTTP_compression"));

    mp_client->request(methods::GET)
    .then([&](http_response response) -> pplx::task<json::value>
    {
        if (response.status_code() == status_codes::OK)
        {
            std::cout << "!!!!200 OK" << std::endl;
        }

    }).wait();

    delete mp_client;

    return true;
}
```
OS: CentOS 7
Boost version: 1.69.0
OpenSSL version: 1.0.2k-19 
GCC: 4.8.5

All ldd result of the execution:
 ```
linux-vdso.so.1 =>  (0x00007ffe72d5e000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f8312125000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f8311f1d000)
        libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f8311aba000)
        libssl.so.10 => /lib64/libssl.so.10 (0x00007f8311848000)
        libboost_system.so.1.69.0 => /lib64/libboost_system.so.1.69.0 (0x00007f8311646000)
        libcpprest.so.2.10 => /lib64/libcpprest.so.2.10 (0x00007f831112f000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f8310e28000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f8310b26000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f8310910000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f83106f4000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f8310326000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f8312329000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f8310110000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f830fec3000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f830fbda000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f830f9d6000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f830f7a3000)
        libboost_random.so.1.69.0 => /usr/local/boost/lib/libboost_random.so.1.69.0 (0x00007f830f59b000)
        libboost_thread.so.1.69.0 => /usr/local/boost/lib/libboost_thread.so.1.69.0 (0x00007f830f37a000)
        libboost_filesystem.so.1.69.0 => /usr/local/boost/lib/libboost_filesystem.so.1.69.0 (0x00007f830f15f000)
        libboost_chrono.so.1.69.0 => /usr/local/boost/lib/libboost_chrono.so.1.69.0 (0x00007f830ef56000)
        libboost_atomic.so.1.69.0 => /usr/local/boost/lib/libboost_atomic.so.1.69.0 (0x00007f830ed54000)
        libboost_date_time.so.1.69.0 => /usr/local/boost/lib/libboost_date_time.so.1.69.0 (0x00007f830eb42000)
        libboost_regex.so.1.69.0 => /usr/local/boost/lib/libboost_regex.so.1.69.0 (0x00007f830e87a000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f830e66a000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f830e466000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f830e24c000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f830e025000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f830ddc3000)
```

If changing "https" to "http", the program will run without issue.

**Comment by dibet** [comment]
Hi, i have the same problem.
Any help?
