### ISSUE TITLE
Running a sample program built in ubuntu 18.04 crashes in 20.04

### ISSUE THREAD

**Issue by kmathewgit** [microsoft/cpprestsdk#1642]
I am building the sample program with cpprestsdk on ubuntu 18.04, but while running on ubuntu 20.04 it crashes with the following stack trace

Thread 3 "sample" received signal SIGSEGV, Segmentation fault
[Switching to Thread 0x7ffff727e700 (LWP 3710880)]
0x00007ffff7deef14 in utility::details::str_iless(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /lib/x86_64-linux-gnu/libcpprest.so.2.10
(gdb) bt
#0 0x00007ffff7deef14 in utility::details::str_iless(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /lib/x86_64-linux-gnu/libcpprest.so.2.10

#1 0x00007ffff7d874f0 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, web::http::http_headers::_case_insensitive_cmp, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::find(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const () from /lib/x86_64-linux-gnu/libcpprest.so.2.10

#2 0x00007ffff7d81078 in web::http::client::http_client::request(web::http::http_request, pplx::cancellation_token const&) ()
from /lib/x86_64-linux-gnu/libcpprest.so.2.10

#3 0x000055555560a939 in web::http::client::http_client::request (this=0x7ffff727d980, mtd="GET", token=...) at /usr/include/cpprest/http_client.h:506

**Comment by barcharcraz** [comment]
This seems like an ABI issue. Note that cpprestsdk does not have a stable ABI, so if 18.04 has a different version than 20.04 that would be bad (tm).

**Comment by kmathewgit** [comment]
The version of cpprestsdk is the same (2.10) in both.
